### ISSUE TITLE
webkitgtk:can not compile

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#117]
[ 80%] Generating ../../DerivedSources/WebKit/PluginProcessConnectionManagerMessageReceiver.cpp, ../../DerivedSources/WebKit/PluginProcessConnectionManagerMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/PluginProxyMessageReceiver.cpp, ../../DerivedSources/WebKit/PluginProxyMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/ServiceWorkerClientFetchMessageReceiver.cpp, ../../DerivedSources/WebKit/ServiceWorkerClientFetchMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/WebSWClientConnectionMessageReceiver.cpp, ../../DerivedSources/WebKit/WebSWClientConnectionMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/WebSWContextManagerConnectionMessageReceiver.cpp, ../../DerivedSources/WebKit/WebSWContextManagerConnectionMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/WebUserContentControllerMessageReceiver.cpp, ../../DerivedSources/WebKit/WebUserContentControllerMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/DrawingAreaMessageReceiver.cpp, ../../DerivedSources/WebKit/DrawingAreaMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/EventDispatcherMessageReceiver.cpp, ../../DerivedSources/WebKit/EventDispatcherMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/RemoteWebInspectorUIMessageReceiver.cpp, ../../DerivedSources/WebKit/RemoteWebInspectorUIMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/VisitedLinkTableControllerMessageReceiver.cpp, ../../DerivedSources/WebKit/VisitedLinkTableControllerMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/WebInspectorMessageReceiver.cpp, ../../DerivedSources/WebKit/WebInspectorMessages.h
[ 80%] Generating ../../DerivedSources/WebKit/WebInspectorInterruptDispatcherMessageReceiver.cpp, ../../DerivedSources/WebKit/WebInspectorInterruptDispatcherMessages.h
[ 81%] Generating ../../DerivedSources/WebKit/WebInspectorUIMessageReceiver.cpp, ../../DerivedSources/WebKit/WebInspectorUIMessages.h
[ 81%] Generating ../../DerivedSources/WebKit/WebPageMessageReceiver.cpp, ../../DerivedSources/WebKit/WebPageMessages.h
[ 81%] Generating ../../DerivedSources/WebKit/StorageAreaMapMessageReceiver.cpp, ../../DerivedSources/WebKit/StorageAreaMapMessages.h
[ 81%] Generating ../../DerivedSources/WebKit/LegacyCustomProtocolManagerMessageReceiver.cpp, ../../DerivedSources/WebKit/LegacyCustomProtocolManagerMessages.h
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSInternals.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSMallocStatistics.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSMemoryInfo.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSMockCDMFactory.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSMockContentFilterSettings.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSMockPageOverlay.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSServiceWorkerInternals.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSTypeConversions.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSInternalSettingsGenerated.cpp.o
[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/InternalSettingsGenerated.cpp.o
Traceback (most recent call last):
  File "/usr/src/webkitgtk-2.22.6/webkit2gtk3-oosb/DerivedSources/ForwardingHeaders/JavaScriptCore/Scripts/cssmin.py", line 49, in <module>
    sys.stdout.write(cssminify(sys.stdin.read()))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 23107: ordinal not in range(128)
Failed to minify /usr/src/webkitgtk-2.22.6/webkit2gtk3-oosb/DerivedSources/WebInspectorUI/Main.css: Inappropriate ioctl for device at /usr/src/webkitgtk-2.22.6/Source/WebInspectorUI/Scripts/copy-user-interface-resources.pl line 385.
make[2]: *** [Source/WebKit/CMakeFiles/WebKit.dir/build.make:2261: inspector-resources.stamp] Error 25
make[1]: *** [CMakeFiles/Makefile2:1403: Source/WebKit/CMakeFiles/WebKit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 81%] Linking CXX static library ../../lib/libWebCoreTestSupport.a
[ 81%] Built target WebCoreTestSupport
make: *** [Makefile:152: all] Error 2
Creating /var/log/lunar/compile/webkit2gtk3-2.22.6.xz

**Comment by lazyape** [comment]
Hi @lhw828, also you had something similar to issue https://github.com/lunar-linux/moonbase-gnome3/issues/87.

can you inform us about your LANG variable?

**Comment by lazyape** [comment]
i can compile webkit2gtk3 correctly, my LANG=en_US.utf8
also i build my webkit2gtk3 with this under /var/state/lunar/depends

ghatz@antipirinas ~ $ grep ^webkit2gtk3 /var/state/lunar/depends
webkit2gtk3:cmake:on:required::
webkit2gtk3:ruby:on:required::
webkit2gtk3:which:on:required::
webkit2gtk3:libjpeg-turbo:on:required::
webkit2gtk3:libpng:on:required::
webkit2gtk3:libwebp:on:required::
webkit2gtk3:mesa-lib:on:required::
webkit2gtk3:icu4c:on:required::
webkit2gtk3:enchant:on:required::
webkit2gtk3:libXt:on:required::
webkit2gtk3:libxslt:on:required::
webkit2gtk3:gobject-introspection:on:required::
webkit2gtk3:harfbuzz:on:required::
webkit2gtk3:freetype2:on:required::
webkit2gtk3:gtk+-3:on:required::
webkit2gtk3:gst-plugins-bad:on:required::
webkit2gtk3:gperf:on:required::
webkit2gtk3:sqlite:on:required::
webkit2gtk3:libsoup:on:required::
webkit2gtk3:libsecret:on:required::
webkit2gtk3:wayland-protocols:on:required::
webkit2gtk3:upower:on:required::
webkit2gtk3:zlib:on:required::
webkit2gtk3:hyphen:off:optional:-DUSE_LIBHYPHEN=ON:-DUSE_LIBHYPHEN=OFF
webkit2gtk3:libnotify:on:optional:-DUSE_LIBNOTIFY=ON:-DUSE_LIBNOTIFY=OFF
webkit2gtk3:geoclue2:on:optional:-DENABLE_GEOLOCATION=ON:-DENABLE_GEOLOCATION=OF                                                                                              F
webkit2gtk3:wayland:on:optional:-DENABLE_WAYLAND_TARGET=ON:-DENABLE_WAYLAND_TARG                                                                                              ET=OFF
webkit2gtk3:gtk-doc:off:optional:-DENABLE_GTKDOC=ON:-DENABLE_GTKDOK=OFF
webkit2gtk3:gtk+-2:off:optional:-DENABLE_PLUGIN_PROCESS_GTK2=ON:-DENABLE_PLUGIN_                                                                                              PROCESS_GTK2=OFF

**Comment by lhw828** [comment]
bash-4.4# grep ^webkit2gtk3 /var/state/lunar/depends
webkit2gtk3:cmake:on:required::
webkit2gtk3:ruby:on:required::
webkit2gtk3:which:on:required::
webkit2gtk3:libjpeg-turbo:on:required::
webkit2gtk3:libpng:on:required::
webkit2gtk3:libwebp:on:required::
webkit2gtk3:mesa-lib:on:required::
webkit2gtk3:icu4c:on:required::
webkit2gtk3:enchant:on:required::
webkit2gtk3:libXt:on:required::
webkit2gtk3:libxslt:on:required::
webkit2gtk3:gobject-introspection:on:required::
webkit2gtk3:harfbuzz:on:required::
webkit2gtk3:freetype2:on:required::
webkit2gtk3:gtk+-3:on:required::
webkit2gtk3:gst-plugins-bad:on:required::
webkit2gtk3:gperf:on:required::
webkit2gtk3:sqlite:on:required::
webkit2gtk3:libsoup:on:required::
webkit2gtk3:libsecret:on:required::
webkit2gtk3:wayland-protocols:on:required::
webkit2gtk3:upower:on:required::
webkit2gtk3:zlib:on:required::
webkit2gtk3:hyphen:on:optional:-DUSE_LIBHYPHEN=ON:-DUSE_LIBHYPHEN=OFF
webkit2gtk3:libnotify:on:optional:-DUSE_LIBNOTIFY=ON:-DUSE_LIBNOTIFY=OFF
webkit2gtk3:geoclue2:on:optional:-DENABLE_GEOLOCATION=ON:-DENABLE_GEOLOCATION=OFF
webkit2gtk3:wayland:on:optional:-DENABLE_WAYLAND_TARGET=ON:-DENABLE_WAYLAND_TARGET=OFF
webkit2gtk3:gtk-doc:on:optional:-DENABLE_GTKDOC=ON:-DENABLE_GTKDOK=OFF

**Comment by lhw828** [comment]
bash-4.4# cat /etc/locale.conf 
LANG=en_US.utf8
LC_ALL=en_US.utf8

**Comment by lhw828** [comment]
I even reinstalled the system once to install webkit2gtk3. But there are still problems.

**Comment by lazyape** [comment]
Hi @lhw828, i am able to compile webkit2gtk3 without gtk-doc. With gtk-doc dependency enabled i get
compilation error due to a missing dependency (python-configparser) which is needed from a python
script in order to generate the docs. I still trying to understand why it is failing on your side, i will come back later after my investigation is done

**Comment by lhw828** [comment]
Select gtk-doc dependency or close without gtk-doc dependency. I tried both, but failed to compile properly.

**Comment by lazyape** [comment]
the problem you have is not in the gtk-doc currently.
please try these.

```cd ....../webkit2gtk3-oosb
   sudo /usr/bin/python2 DerivedSources/ForwardingHeaders/JavaScriptCore/Scripts/cssmin.py < ../Source/WebCore/xml/XMLViewer.css > DerivedSources/WebCore/XMLViewer.min.css   
```

is the command above failing with the same error?

**Comment by lhw828** [comment]
Can you write this command in Build? Or patches?

At first, after I executed this command, the system downloaded webkit2gtk3 again.

bash-4.4# cd /usr/src/webkitgtk-2.22.6/webkit2gtk3-oosb/
bash-4.4# /usr/bin/python2 DerivedSources/ForwardingHeaders/JavaScriptCore/Scripts/cssmin.py < ../Source/WebCore/xml/XMLViewer.css > DerivedSources/WebCore/XMLViewer.min.css   

bash-4.4# lin webkit2gtk3
Checking dependencies for
Downloading source file webkitgtk-2.22.6.tar.xz for module webkit2gtk3
--2019-02-28 21:57:52--  https://www.webkitgtk.org/releases/webkitgtk-2.22.6.tar.xz
Resolving www.webkitgtk.org... 91.121.216.36
Connecting to www.webkitgtk.org|91.121.216.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16773696 (16M) [application/x-xz]
Saving to: '/tmp/webkitgtk-2.22.6.tar.xz'

/tmp/webkitgtk-2.22 100%[===================>]  16.00M  22.3KB/s    in 11m 20s 

2019-02-28 22:09:17 (24.1 KB/s) - '/tmp/webkitgtk-2.22.6.tar.xz' saved [16773696/16773696]

When I try again, the prompt is: No such file or directory.

bash-4.4# /usr/bin/python2 DerivedSources/ForwardingHeaders/JavaScriptCore/Scripts/cssmin.py < ../Source/WebCore/xml/XMLViewer.css > DerivedSources/WebCore/XMLViewer.min.css 
bash: DerivedSources/WebCore/XMLViewer.min.css:

**Comment by lazyape** [comment]
i cannot understand what you say 
"At first, after I executed this command, the system downloaded webkit2gtk3 again".

In general there seems to be a problem in your installation. some missing dependency probably,
which we try to figure out, cause i am able to build it without gtk-doc. but the problem you have
is NOT in gtk-doc, it is in the WebCore directory, so i don't have the error you have.

@Florin65 am i allowed to add a patch in the webkit2gtk3 package in order to add verbosity on @lhw828  build and see if we can catch something?

till Florin65 answers we can continue like this.
build webkit (it will fail).
then in a terminal
```
lsh
cd $BUILD_DIRECTORY/webkitgtk-2.22.6/webkit2gtk3-oosb
make -j1 VERBOSE=1
```

and then share the output by pasting it to github gist and pointing the url here

**Comment by lhw828** [comment]
I successfully executed that command and then installed webkit2gtk3. The log file is as follows.
[webkit2gtk3.log](https://github.com/lunar-linux/moonbase-gnome3/files/2915474/webkit2gtk3.log)

**Comment by lhw828** [comment]
bash-4.4# lsh            
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

    Warning: lsh is potentially hazardous to your system.

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
[lunar] root@lhw /usr/src/webkitgtk-2.22.6/webkit2gtk3-oosb # make -j1 VERBOSE=1make: getcwd: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
[lunar] root@lhw /usr/src/webkitgtk-2.22.6/webkit2gtk3-oosb #

**Comment by lazyape** [comment]
i don't want the log you sent me. 
I want the log produced by 
make -j1 VERBOSE=1

if you are in the webkit2gtk3-oosb/ the lsh is not needed. 
so
cd webkit2gtk3-oosb/
make -j1 VERBOSE=1

then paste the log

regards

**Comment by lhw828** [comment]
https://gist.github.com/lhw828/224cfbfdd13a036de678598e5924ff65

**Comment by lazyape** [comment]
@lhw828 , the error is somewhere in python and its unicode submodule.
please provide me the output of command `locale`. i will update mines as yours
and try to reproduce the problem. I don't have any other way to help currently.
regards

**Comment by lhw828** [comment]
![_20190301223316](https://user-images.githubusercontent.com/1897722/53645489-f1f85480-3c73-11e9-8a55-78089837d38e.jpg)

**Comment by lazyape** [comment]
hi @lhw828 
i've manage to reproduce the problem. i switch my LANG, LC_* variables to the same as yours and i hit the same error.
i think that webkit2gtk3 needs a .utf8 LC_*, LANG variables not plain.
so i propose you to switch to en_US.utf8 by executing 
export LANG=en_US.utf8
in case that some LC_* variable don't switch to .utf8 it means that it is already set in the current shell so 
unset LC_<name> will turn its value to en_US.utf8

i will add a check in webkit2gtk3 too

cheers

**Comment by lhw828** [comment]
Finally,you solved the problem.
Thank you VERY MUCH～～～！！！

**Comment by lhw828** [comment]
How can we solve this problem once and for all? The patch? Installation tips?

**Comment by lazyape** [comment]
PR created
https://github.com/lunar-linux/moonbase-gnome3/pull/120

**Comment by florin65** [comment]
Fixed.
