### ISSUE TITLE
gtk+-3-24.9:some errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#141]
Building gtk+-3 version 24.9
patching file gtk/gtkfilechooserprivate.h
patching file gtk/gtkfilechooserwidget.c
Hunk #2 succeeded at 44 (offset 1 line).
Hunk #3 succeeded at 82 (offset 1 line).
Hunk #4 succeeded at 200 (offset 1 line).
Hunk #5 succeeded at 229 (offset 1 line).
Hunk #6 succeeded at 265 (offset 1 line).
Hunk #7 succeeded at 350 (offset 1 line).
Hunk #8 succeeded at 423 (offset 1 line).
Hunk #9 succeeded at 443 (offset 1 line).
Hunk #10 succeeded at 454 (offset 1 line).
Hunk #11 succeeded at 578 (offset 1 line).
Hunk #12 succeeded at 586 (offset 1 line).
Hunk #13 succeeded at 605 (offset 1 line).
Hunk #14 succeeded at 641 (offset 1 line).
Hunk #15 succeeded at 996 (offset 1 line).
Hunk #16 succeeded at 1264 (offset 1 line).
Hunk #17 succeeded at 1396 (offset 1 line).
Hunk #18 succeeded at 1499 (offset 1 line).
Hunk #19 succeeded at 2316 (offset 1 line).
Hunk #20 succeeded at 2410 (offset 1 line).
Hunk #21 succeeded at 2420 (offset 1 line).
Hunk #22 succeeded at 2466 (offset 1 line).
Hunk #23 succeeded at 2475 (offset 1 line).
Hunk #24 succeeded at 2506 (offset 1 line).
Hunk #25 succeeded at 2537 (offset 1 line).
Hunk #26 succeeded at 2566 (offset 1 line).
Hunk #27 succeeded at 2593 (offset 1 line).
Hunk #28 succeeded at 2878 (offset 1 line).
Hunk #29 succeeded at 2949 (offset 1 line).
Hunk #30 succeeded at 3096 (offset 1 line).
Hunk #31 succeeded at 3168 (offset 1 line).
Hunk #32 succeeded at 3299 (offset 1 line).
Hunk #33 succeeded at 3329 (offset 1 line).
Hunk #34 succeeded at 3454 (offset 1 line).
Hunk #35 succeeded at 3468 (offset 1 line).
Hunk #36 succeeded at 3898 (offset 1 line).
Hunk #37 succeeded at 4020 (offset 1 line).
Hunk #38 succeeded at 4035 (offset 1 line).
Hunk #39 succeeded at 4048 (offset 1 line).
Hunk #40 succeeded at 4059 (offset 1 line).
Hunk #41 succeeded at 4096 (offset 1 line).
Hunk #42 succeeded at 4572 (offset 1 line).
Hunk #43 succeeded at 4659 (offset 1 line).
Hunk #44 succeeded at 4678 (offset 1 line).
Hunk #45 succeeded at 4704 (offset 1 line).
Hunk #46 succeeded at 4718 (offset 1 line).
Hunk #47 succeeded at 4731 (offset 1 line).
Hunk #48 succeeded at 4739 (offset 1 line).
Hunk #49 succeeded at 4794 (offset 1 line).
Hunk #50 succeeded at 4918 (offset 1 line).
Hunk #51 succeeded at 5103 (offset 1 line).
Hunk #52 succeeded at 5174 (offset 1 line).
Hunk #53 succeeded at 5236 (offset 1 line).
Hunk #54 succeeded at 5488 (offset 1 line).
Hunk #55 succeeded at 5504 (offset 1 line).
Hunk #56 succeeded at 6002 (offset 1 line).
Hunk #57 succeeded at 6021 (offset 1 line).
Hunk #58 succeeded at 6032 (offset 1 line).
Hunk #59 succeeded at 6050 (offset 1 line).
Hunk #60 succeeded at 6071 (offset 1 line).
Hunk #61 succeeded at 6227 (offset 1 line).
Hunk #62 succeeded at 6267 (offset 1 line).
Hunk #63 succeeded at 6545 (offset 1 line).
Hunk #64 succeeded at 6555 (offset 1 line).
Hunk #65 succeeded at 6573 (offset 1 line).
Hunk #66 succeeded at 7092 (offset 1 line).
Hunk #67 succeeded at 7339 (offset 1 line).
Hunk #68 succeeded at 7377 (offset 1 line).
Hunk #69 succeeded at 7465 (offset 1 line).
Hunk #70 succeeded at 7491 (offset 1 line).
Hunk #71 succeeded at 7700 (offset 1 line).
Hunk #72 succeeded at 7753 (offset 1 line).
Hunk #73 succeeded at 7900 (offset 21 lines).
Hunk #74 succeeded at 7963 (offset 21 lines).
Hunk #75 succeeded at 8081 (offset 21 lines).
Hunk #76 succeeded at 8111 (offset 21 lines).
Hunk #77 succeeded at 8159 (offset 21 lines).
Hunk #78 succeeded at 8190 (offset 21 lines).
Hunk #79 succeeded at 8772 (offset 21 lines).
Hunk #80 succeeded at 8802 (offset 21 lines).
Hunk #81 succeeded at 8812 (offset 21 lines).
Hunk #82 succeeded at 8827 (offset 21 lines).
Hunk #83 succeeded at 8878 (offset 22 lines).
Hunk #84 succeeded at 8921 with fuzz 2 (offset 22 lines).
Hunk #85 succeeded at 8972 (offset 26 lines).
Hunk #86 succeeded at 8984 (offset 26 lines).
Hunk #87 succeeded at 9032 (offset 26 lines).
Hunk #88 succeeded at 9336 (offset 26 lines).
Hunk #89 succeeded at 9403 (offset 26 lines).
patching file gtk/org.gtk.Settings.FileChooser.gschema.xml
patching file gtk/ui/gtkfilechooserwidget.ui
usage: meson [-h]
             {setup,configure,install,introspect,init,test,wrap,subprojects,help,rewrite}
             ...
meson: error: unrecognized arguments: --enable-broadway-backend
Creating /var/log/lunar/compile/gtk+-3-24.9.xz

**Comment by florin65** [comment]
You have to do a lin -rc gtk+-3.
