### ISSUE TITLE
gnome-icon-theme-symbolic:some errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#183]
Building gnome-icon-theme-symbolic version 3.12.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.19... yes
checking icon-naming-utils >= 0.8.7... yes
checking for gtk-update-icon-cache... /usr/bin/gtk-update-icon-cache
checking for git... /usr/bin/git
checking for icontool-render... false
checking for inkscape... false
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating gnome-icon-theme-symbolic.pc
config.status: creating Makefile
config.status: creating src/Makefile
Making all in src
make[1]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0/src'
if test "x.." != "x.."; then \
	cp -a ../gnome ../gnome; \
fi
make[1]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0/src'
make[1]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
Making install in src
make[1]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0/src'
if test "x.." != "x.."; then \
	cp -a ../gnome ../gnome; \
fi
make[2]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0/src'
make[2]: Nothing to be done for 'install-exec-am'.
for size in ; do \
	for file in `cd ../gnome/$size; find . -name "*.png"`; do \
		context="`dirname $file`"; \
		/usr/bin/mkdir -p /usr/share/icons/gnome/$size/$context; \
		/bin/sh /usr/src/gnome-icon-theme-symbolic-3.12.0/install-sh -c -m 644 ../gnome/$size/$file /usr/share/icons/gnome/$size/$file; \
	done; \
done
for file in `cd ../gnome/scalable; find . -name "*.svg"`; do \
	context="`dirname $file`"; \
	/usr/bin/mkdir -p /usr/share/icons/gnome/scalable/$context; \
	/bin/sh /usr/src/gnome-icon-theme-symbolic-3.12.0/install-sh -c -m 644 ../gnome/scalable/$file /usr/share/icons/gnome/scalable/$file; \
done
make[2]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0/src'
make[1]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0/src'
make[1]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
make[2]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
make[2]: Nothing to be done for 'install-exec-am'.
if [ -h /usr/share/icons/gnome ]; then \
	rm -f /usr/share/icons/gnome; \
fi
 /usr/bin/mkdir -p '/usr/share/pkgconfig'
if [ -d /usr/share/icons/gnome ]; then \
	touch /usr/share/icons/gnome; \
fi
 /usr/bin/install -c -m 644 gnome-icon-theme-symbolic.pc '/usr/share/pkgconfig'
/usr/bin/make  install-data-hook
make[3]: Entering directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
if test -z "" ; then \
	/usr/bin/gtk-update-icon-cache -q /usr/share/icons/gnome; \
fi
gtk-update-icon-cache: No theme index file.
make[3]: *** [Makefile:826: install-data-hook] Error 1
make[3]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
make[2]: *** [Makefile:743: install-data-am] Error 2
make[2]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
make[1]: *** [Makefile:695: install-am] Error 2
make[1]: Leaving directory '/usr/src/gnome-icon-theme-symbolic-3.12.0'
make: *** [Makefile:395: install-recursive] Error 1
Creating /var/log/lunar/compile/gnome-icon-theme-symbolic-3.12.0.xz 
! Problem detected during BUILD

**Comment by florin65** [comment]
It's fixed now. Thank you for reporting it.
