### ISSUE TITLE
gnome-terminal:some errors.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#184]
configure: creating ./config.status
config.status: creating Makefile
config.status: creating org.gnome.Terminal.desktop.in
config.status: creating data/Makefile
config.status: creating data/icons/Makefile
config.status: creating src/Makefile
config.status: creating src/terminal-version.h
config.status: creating help/Makefile
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

gnome-terminal-3.34.2:

      prefix:                 /usr
      source code location:   .
      compiler:               gcc
      gterminal:              
      DBus interface dir:     ${datadir}/dbus-1/interfaces
      DBus service dir:       ${datadir}/dbus-1/services
      Debug:                  no
      Search provider:        no
      Nautilus extension:     no
      Nautilus extension dir: 

/usr/bin/make  all-recursive
make[1]: Entering directory '/usr/src/gnome-terminal-3.34.2'
Making all in data
make[2]: Entering directory '/usr/src/gnome-terminal-3.34.2/data'
Making all in icons
make[3]: Entering directory '/usr/src/gnome-terminal-3.34.2/data/icons'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/usr/src/gnome-terminal-3.34.2/data/icons'
make[3]: Entering directory '/usr/src/gnome-terminal-3.34.2/data'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/usr/src/gnome-terminal-3.34.2/data'
make[2]: Leaving directory '/usr/src/gnome-terminal-3.34.2/data'
Making all in src
make[2]: Entering directory '/usr/src/gnome-terminal-3.34.2/src'
  GEN      terminal-marshal.c
  GEN      terminal-marshal.h
  GEN      terminal-type-builtins.c
  GEN      stamp-terminal-type-builtins.h
  GEN      terminal-gdbus-generated.c
INFO: Reading ./terminal-marshal.list...
  GEN      terminal-gdbus-generated.h
INFO: Reading ./terminal-marshal.list...
  GEN      terminal-menubar-with-mnemonics.ui
  GEN      terminal-menubar-without-mnemonics.ui
  GEN      terminal-resources.c
  GEN      terminal-resources.h
/usr/bin/make  all-am
make[3]: Entering directory '/usr/src/gnome-terminal-3.34.2/src'
  CC       gnome_terminal-terminal.o
  CC       gnome_terminal-terminal-client-utils.o
  CC       gnome_terminal-terminal-debug.o
  CC       gnome_terminal-terminal-i18n.o
  CC       gnome_terminal-terminal-options.o
  CC       gnome_terminal-terminal-profiles-list.o
  CC       gnome_terminal-terminal-settings-list.o
  CC       gnome_terminal-terminal-gdbus-generated.o
  CC       gnome_terminal-terminal-type-builtins.o
  CC       gnome_terminal_server-eggshell.o
  CC       gnome_terminal_server-profile-editor.o
  CC       gnome_terminal_server-server.o
  CC       gnome_terminal_server-terminal-accels.o
  CC       gnome_terminal_server-terminal-app.o
  CC       gnome_terminal_server-terminal-debug.o
  CC       gnome_terminal_server-terminal-encoding.o
  CC       gnome_terminal_server-terminal-gdbus.o
  CC       gnome_terminal_server-terminal-headerbar.o
server.c: In function 'init_server':
server.c:144:12: warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
  144 |     (void) chdir ("/");
      |            ^~~~~~~~~~~
  CC       gnome_terminal_server-terminal-icon-button.o
  CC       gnome_terminal_server-terminal-info-bar.o
  CC       gnome_terminal_server-terminal-i18n.o
  CC       gnome_terminal_server-terminal-mdi-container.o
  CC       gnome_terminal_server-terminal-menu-button.o
  CC       gnome_terminal_server-terminal-notebook.o
  CC       gnome_terminal_server-terminal-prefs.o
  CC       gnome_terminal_server-terminal-profiles-list.o
  CC       gnome_terminal_server-terminal-settings-list.o
  CC       gnome_terminal_server-terminal-screen.o
  CC       gnome_terminal_server-terminal-screen-container.o
  CC       gnome_terminal_server-terminal-search-popover.o
  CC       gnome_terminal_server-terminal-tab-label.o
  CC       gnome_terminal_server-terminal-util.o
  CC       gnome_terminal_server-terminal-window.o
  CC       gnome_terminal_server-terminal-marshal.o
  CC       gnome_terminal_server-terminal-type-builtins.o
terminal-util.c: In function 'terminal_util_bind_mnemonic_label_sensitivity':
terminal-util.c:973:28: warning: cast between incompatible function types from 'void (*)(GtkWidget *)' {aka 'void (*)(struct _GtkWidget *)'} to 'void (*)(GtkWidget *, void *)' {aka 'void (*)(struct _GtkWidget *, void *)'} [-Wcast-function-type]
  973 |                            (GtkCallback) terminal_util_bind_mnemonic_label_sensitivity,
      |                            ^
In file included from /usr/include/string.h:494,
                 from terminal-util.c:24:
In function 'strncpy',
    inlined from 'add_separators.part.0' at terminal-util.c:1000:5:
/usr/include/bits/string_fortified.h:106:10: warning: '__builtin_strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
terminal-util.c: In function 'add_separators.part.0':
terminal-util.c:990:12: note: length computed here
  990 |   seplen = strlen(sep);
      |            ^~~~~~~~~~~
  CC       gnome_terminal_server-terminal-gdbus-generated.o
  CC       gnome_terminal_server-terminal-resources.o
  GEN      org.gnome.Terminal.service
  GEN      gnome-terminal-server.service
  GEN      org.gnome.Terminal.gschema.valid
  CCLD     gnome-terminal
  CCLD     gnome-terminal-server
/usr/bin/ld: gnome_terminal-terminal-settings-list.o: in function `terminal_settings_list_add_child_internal':
terminal-settings-list.c:(.text+0x243): undefined reference to `dconf_changeset_new'
/usr/bin/ld: terminal-settings-list.c:(.text+0x2e0): undefined reference to `dconf_changeset_set'
/usr/bin/ld: terminal-settings-list.c:(.text+0x354): undefined reference to `dconf_changeset_set'
/usr/bin/ld: terminal-settings-list.c:(.text+0x37b): undefined reference to `dconf_changeset_unref'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1153: gnome-terminal] Error 1
make[3]: *** Waiting for unfinished jobs....
/usr/bin/ld: gnome_terminal_server-terminal-settings-list.o: in function `terminal_settings_list_add_child_internal':
terminal-settings-list.c:(.text+0x243): undefined reference to `dconf_changeset_new'
/usr/bin/ld: terminal-settings-list.c:(.text+0x2e0): undefined reference to `dconf_changeset_set'
/usr/bin/ld: terminal-settings-list.c:(.text+0x354): undefined reference to `dconf_changeset_set'
/usr/bin/ld: terminal-settings-list.c:(.text+0x37b): undefined reference to `dconf_changeset_unref'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1157: gnome-terminal-server] Error 1
make[3]: Leaving directory '/usr/src/gnome-terminal-3.34.2/src'
make[2]: *** [Makefile:961: all] Error 2
make[2]: Leaving directory '/usr/src/gnome-terminal-3.34.2/src'
make[1]: *** [Makefile:589: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/gnome-terminal-3.34.2'
make: *** [Makefile:477: all] Error 2
Creating /var/log/lunar/compile/gnome-terminal-3.34.2.xz

It seems that Gnome still has a lot of work to do.

**Comment by florin65** [comment]
Fixed. It was the PRE_BUILD file from dconf module fault.
