### ISSUE TITLE
gnome-desktop:build errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#199]
Installing /usr/src/gnome-desktop-3.36.0/libgnome-desktop/gnome-idle-monitor.h to /usr/include/gnome-desktop-3.0/libgnome-desktop
Installing /usr/src/gnome-desktop-3.36.0/libgnome-desktop/gnome-languages.h to /usr/include/gnome-desktop-3.0/libgnome-desktop
Installing /usr/src/gnome-desktop-3.36.0/build/gnome-version.xml to /usr/share/gnome
Installing /usr/src/gnome-desktop-3.36.0/build/meson-private/gnome-desktop-3.0.pc to /usr/lib/pkgconfig
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=gnome-desktop-3.0'
Running custom install script '/usr/bin/meson --internal yelphelper install --subdir=desktop-docs/fdl --id=fdl --installdir=share/help --sources=index.docbook --symlinks=true'
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
Creating /var/log/lunar/compile/gnome-desktop-3.36.0.xz

**Comment by lazyape** [comment]
Hi lhw828.
Can you please attach the entire log? I cannot understand from the text above where is the problem

**Comment by lhw828** [comment]
[gnome-desktop-3.36.0.log](https://githu@lazyape .com/lunar-linux/moonbase-gnome3/files/4332561/gnome-desktop-3.36.0.log)
@lazyape

**Comment by lhw828** [comment]
gnome-desktop It looks like need ‘libxml2’

**Comment by lazyape** [comment]
@lhw828, @florin65  libxml2 is not a direct dependency of gnome-desktop.
Neither xml2, -lxml nor any of libxml2 binaries {xml2-config, xmlcatalog,xmllint } are used directly from gnome-desktop's code.
I propose removing the hard dependency. @lhw828 it is better dig more and see where we've miss libxml2 dependency on another package instead of gnome-desktop
