### ISSUE TITLE
mutter looks like need pipewire

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#201]
Building mutter version 3.36.0
The Meson build system
Version: 0.53.1
Source dir: /usr/src/mutter-3.36.0
Build dir: /usr/src/mutter-3.36.0/build
Build type: native build
Project name: mutter
Project version: 3.36.0
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending LDFLAGS from environment: ['-s']
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending LDFLAGS from environment: ['-s']
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
C compiler for the host machine: gcc (gcc 9.2.0 "gcc (GCC) 9.2.0")
C linker for the host machine: gcc GNU ld.bfd 2.33.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency x11 found: YES 1.6.7
Run-time dependency graphene-gobject-1.0 found: YES 1.10.0
Run-time dependency gtk+-3.0 found: YES 3.24.14
Run-time dependency gdk-pixbuf-2.0 found: YES 2.40.0
Run-time dependency pango found: YES 1.44.7
Run-time dependency cairo found: YES 1.16.0
Run-time dependency cairo-gobject found: YES 1.16.0
Run-time dependency pangocairo found: YES 1.44.7
Run-time dependency fribidi found: YES 1.0.9
Run-time dependency gsettings-desktop-schemas found: YES 3.36.0
Run-time dependency glib-2.0 found: YES 2.62.4
Run-time dependency gio-unix-2.0 found: YES 2.62.4
Dependency gio-unix-2.0 found: YES 2.62.4 (cached)
Run-time dependency gobject-2.0 found: YES 2.62.4
Dependency gobject-2.0 found: YES 2.62.4 (cached)
Run-time dependency gmodule-no-export-2.0 found: YES 2.62.4
Run-time dependency gnome-settings-daemon found: YES 3.36.0
Run-time dependency json-glib-1.0 found: YES 1.4.4
Run-time dependency gnome-desktop-3.0 found: YES 3.36.0
Run-time dependency xcomposite found: YES 0.4.5
Run-time dependency xcursor found: YES 1.2.0
Run-time dependency xdamage found: YES 1.1.5
Run-time dependency xext found: YES 1.3.4
Run-time dependency xfixes found: YES 5.0.3
Run-time dependency xi found: YES 1.7.9
Run-time dependency xtst found: YES 1.2.3
Run-time dependency xkbfile found: YES 1.1.0
Run-time dependency xkeyboard-config found: YES 2.29
Run-time dependency xkbcommon found: YES 0.10.0
Run-time dependency xkbcommon-x11 found: YES 0.10.0
Run-time dependency xrender found: YES 0.9.10
Run-time dependency x11-xcb found: YES 1.6.7
Run-time dependency xrandr found: YES 1.5.2
Run-time dependency xcb-randr found: YES 1.14
Run-time dependency xcb-res found: YES 1.14
Run-time dependency xinerama found: YES 1.1.4
Run-time dependency xau found: YES 1.0.9
Run-time dependency ice found: YES 1.0.10
Run-time dependency atk found: YES 2.34.1
Run-time dependency libcanberra found: YES 0.30
Run-time dependency dbus-1 found: YES 1.13.12
Run-time dependency gl found: YES 1.2
Run-time dependency egl found: YES 1.5
Run-time dependency glesv2 found: YES 3.2
Run-time dependency wayland-server found: YES 1.18.0
Run-time dependency wayland-client found: YES 1.18.0
Run-time dependency wayland-protocols found: YES 1.20
Run-time dependency wayland-egl found: YES 18.1.0
Run-time dependency libudev found: YES 244
Run-time dependency gudev-1.0 found: YES 233
Run-time dependency libdrm found: YES 2.4.100
Run-time dependency gbm found: YES 20.0.1
Run-time dependency libinput found: YES 1.15.3
Run-time dependency libsystemd found: YES 244
Run-time dependency sm found: YES 1.2.3
Run-time dependency pangoft2 found: YES 1.44.7
Run-time dependency libstartup-notification-1.0 found: YES 0.12
Found CMake: /usr/bin/cmake (3.16.5)
Appending CXXFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending LDFLAGS from environment: ['-s']
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Appending LDFLAGS from environment: ['-s']
Run-time dependency libpipewire-0.3 found: NO (tried pkgconfig and cmake)

meson.build:248:2: ERROR: Dependency "libpipewire-0.3" not found, tried pkgconfig and cmake

A full log can be found at /usr/src/mutter-3.36.0/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/mutter-3.36.0.xz

In fact I have installed pipewire yet.

**Comment by v4hn** [comment]
Where's the patch then? :)

**Comment by lhw828** [comment]
Florin has patched pipewire, but it still has problems.

https://github.com/lunar-linux/moonbase-other/issues/1422

**Comment by v4hn** [comment]
> In fact I have installed pipewire yet.

Sorry, I missed the fact that mutter already depends on pipewire and just can't find it.
You can look at (roughly the end of) /usr/src/mutter-3.36.0/build/meson-logs/meson-log.txt and try to find what's going wrong.

**Comment by lhw828** [comment]
Building pipewire version 0.3.1
The Meson build system
Version: 0.53.1
Source dir: /usr/src/pipewire-0.3.1
Build dir: /usr/src/pipewire-0.3.1/build
Build type: native build
Project name: pipewire
Project version: 0.3.1
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe - Wformat'
Appending LDFLAGS from environment: ['-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now']
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'

meson.build:1:0: ERROR: Unable to determine dynamic linker

**Comment by lhw828** [comment]
CFLAGS+=" - Wformat"

It seems like a space is superfluous
