### ISSUE TITLE
cant install gnome-icon-theme-symbolic

### ISSUE THREAD

**Issue by grondinm** [lunar-linux/moonbase-gnome3#21]

**Comment by grondinm** [comment]
When I try to install it fails when doing 

/just/bin/gtk-update-icon-cache -q /usr/share/icons/gnome

Saying gtk-update-icon-cache: No theme index file.

Seems it would have to include the -t flag to gtk-update-icon-cache just not sure how to get it to do that

**Comment by Florin65** [comment]
it works now. it seems the new version og gtk+-3 solved the issue.
