### ISSUE TITLE
mutter:some errors.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#215]
[452/1426] Compiling C object 'src/25a6634@@mutter-6@sha/backends_x11_meta-input-device-x11.c.o'.
FAILED: src/25a6634@@mutter-6@sha/backends_x11_meta-input-device-x11.c.o 
gcc -Isrc/25a6634@@mutter-6@sha -Isrc -I../src -I. -I../ -Iclutter -I../clutter -Iclutter/clutter -I../clutter/clutter -Icogl -I../cogl -Icogl/cogl -I../cogl/cogl -Isrc/meta -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/json-glib-1.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/gsettings-desktop-schemas -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/gnome-desktop-3.0 -I/usr/include/gnome-settings-daemon-3.0 -I/usr/include/gudev-1.0 -I/usr/include/startup-notification-1.0 -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/gobject-introspection-1.0 -I/usr/include/libdrm -fvisibility=hidden -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -D_GNU_SOURCE -fno-strict-aliasing -Wpointer-arith -Wmissing-declarations -Wimplicit-function-declaration -Wformat=2 -Wformat-nonliteral -Wformat-security -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wundef -Wunused -Wcast-align -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-include-dirs -Wlogical-op -Wignored-qualifiers -Werror=redundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=empty-body -Werror=write-strings -O2 -march=x86-64 -D_FORTIFY_SOURCE=2 -fPIC -pthread -D_REENTRANT -mfpmath=sse -msse -msse2 -DCLUTTER_ENABLE_COMPOSITOR_API -DCLUTTER_ENABLE_EXPERIMENTAL_API -DCOGL_ENABLE_EXPERIMENTAL_API -DCOGL_ENABLE_EXPERIMENTAL_2_0_API -DCOGL_ENABLE_MUTTER_API -DCLUTTER_DISABLE_DEPRECATION_WARNINGS -DCOGL_DISABLE_DEPRECATION_WARNINGS '-DG_LOG_DOMAIN="mutter"' -DSN_API_NOT_YET_FROZEN=1 '-DGETTEXT_PACKAGE="mutter"' -DWITH_VERBOSE_MODE -MD -MQ 'src/25a6634@@mutter-6@sha/backends_x11_meta-input-device-x11.c.o' -MF 'src/25a6634@@mutter-6@sha/backends_x11_meta-input-device-x11.c.o.d' -o 'src/25a6634@@mutter-6@sha/backends_x11_meta-input-device-x11.c.o' -c ../src/backends/x11/meta-input-device-x11.c
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/pango-1.0/pango/pango-coverage.h:25,
                 from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from ../clutter/clutter/clutter-backend.h:32,
                 from ../clutter/clutter/clutter-mutter.h:28,
                 from ../src/backends/x11/meta-input-device-x11.c:24:
../src/backends/x11/meta-input-device-x11.c: In function 'meta_input_device_x11_finalize':
../src/backends/x11/meta-input-device-x11.c:132:23: error: 'device_xi2' undeclared (first use in this function)
  132 |   g_clear_handle_id (&device_xi2->inhibit_pointer_query_timer, g_source_remove);
      |                       ^~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:738:47: note: in definition of macro 'G_STATIC_ASSERT'
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                                               ^~~~
../src/backends/x11/meta-input-device-x11.c:132:3: note: in expansion of macro 'g_clear_handle_id'
  132 |   g_clear_handle_id (&device_xi2->inhibit_pointer_query_timer, g_source_remove);
      |   ^~~~~~~~~~~~~~~~~
../src/backends/x11/meta-input-device-x11.c:132:23: note: each undeclared identifier is reported only once for each function it appears in
  132 |   g_clear_handle_id (&device_xi2->inhibit_pointer_query_timer, g_source_remove);
      |                       ^~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:738:47: note: in definition of macro 'G_STATIC_ASSERT'
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                                               ^~~~
../src/backends/x11/meta-input-device-x11.c:132:3: note: in expansion of macro 'g_clear_handle_id'
  132 |   g_clear_handle_id (&device_xi2->inhibit_pointer_query_timer, g_source_remove);
      |   ^~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmain.h:716:22: error: expression in static assertion is not an integer
  716 |     G_STATIC_ASSERT (sizeof *(tag_ptr) == sizeof (guint)); \
      |                      ^~~~~~
/usr/include/glib-2.0/glib/gmacros.h:738:47: note: in definition of macro 'G_STATIC_ASSERT'
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                                               ^~~~
../src/backends/x11/meta-input-device-x11.c:132:3: note: in expansion of macro 'g_clear_handle_id'
  132 |   g_clear_handle_id (&device_xi2->inhibit_pointer_query_timer, g_source_remove);
      |   ^~~~~~~~~~~~~~~~~
[453/1426] Compiling C object 'src/25a6634@@mutter-6@sha/backends_x11_cm_meta-cursor-sprite-xfixes.c.o'.
[454/1426] Compiling C object 'src/25a6634@@mutter-6@sha/backends_x11_meta-cursor-renderer-x11.c.o'.
[455/1426] Compiling C object 'src/25a6634@@mutter-6@sha/backends_x11_meta-crtc-xrandr.c.o'.
[456/1426] Compiling C object 'src/25a6634@@mutter-6@sha/backends_x11_meta-event-x11.c.o'.
[457/1426] Compiling C object 'src/25a6634@@mutter-6@sha/backends_x11_meta-clutter-backend-x11.c.o'.
ninja: build stopped: subcommand failed.

**Comment by v4hn** [comment]
I actually fixed this unaware of this bug report the other day.
It was already fixed upstream and I pulled the patch into the module.
