### ISSUE TITLE
request for Network-Manager: enable nmtui?

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-gnome3#39]
Hello maintainer of NM, I found out on the Internet, that NM has a nifty text based interface now. It's called 

> nmtui

 and you can completely setup your internet needs with it, without the need of a X server.
The only thing for this is a switch --with-nmtui

I have installed nmtui with the --opts --with-nmtui command. Which works ok.
Here is some more information:
[lfs - networkmanager with nmtui](http://www.linuxfromscratch.org/blfs/view/8.0/basicnet/networkmanager.html)

**Comment by Florin65** [comment]
Added the option into the BUILD file.
Thank you for the tip.
