### ISSUE TITLE
cjs-3.6.1 Compile Error

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#41]
[cjs-3.6.1.log](https://github.com/lunar-linux/moonbase-gnome3/files/1504684/cjs-3.6.1.log)

> checking whether ln -s works... yes
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for gawk... (cached) gawk
./configure: line 16391: AX_COMPILER_FLAGS: command not found
checking whether to build with code coverage support... no
./configure: line 16629: syntax error near unexpected token `-lgcov,,'
./configure: line 16629: `AX_CHECK_LINK_FLAG(-lgcov,,'

>

**Comment by lhw828** [comment]
There is a problem, cjs need mozjs-38, but the system is installed by default the latest mozjs-45.

**Comment by Florin65** [comment]
Current version in the moonbase is now 3.8.0.
