### ISSUE TITLE
 "ModemManager" "1.6.12" mm-base-manager.c: In function 'handle_set_logging':

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#51]
`++ Mark Compile start  : "ModemManager" "1.6.12" "Fri, 18 May 2018 10:17:37 +0000"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... cpp
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /var/lib/lunar/compilers/ld
checking if the linker (/var/lib/lunar/compilers/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /var/lib/lunar/compilers/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/var/lib/lunar/compilers/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking pkg-config is at least version 0.9.0... yes
checking for gtk-doc... yes
checking for gtkdoc-check... gtkdoc-check.test
checking for gtkdoc-check... /usr/bin/gtkdoc-check
checking for gtkdoc-rebase... /usr/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /usr/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... no
checking for glib-2.0 >= 2.10.0 gobject-2.0  >= 2.10.0... yes
checking whether NLS is requested... yes
checking for intltool >= 0.40.0... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.26.2
checking for XML::Parser... ok
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for msgmerge... (cached) /usr/bin/msgmerge
checking for ld used by gcc... /var/lib/lunar/compilers/ld -m elf_x86_64
checking if the linker (/var/lib/lunar/compilers/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for glib-2.0 >= 2.36.0
                  gmodule-2.0
                  gobject-2.0
                  gio-2.0
                  gio-unix-2.0... yes
checking for glib-2.0 >= 2.36.0
                  gobject-2.0
                  gio-2.0
                  gio-unix-2.0... yes
checking for glib-2.0 >= 2.36.0
                  gobject-2.0
                  gio-2.0... yes
checking for gudev-1.0 >= 147... yes
checking whether to build with code coverage support... no
checking for gobject-introspection... yes
checking pkg-config is at least version 0.9.0... yes
checking for vapigen... yes
checking for libsystemd >= 209... yes
checking for libsystemd-login >= 183... no
checking for polkit-gobject-1 >= 0.97... yes
checking for mbim-glib >= 1.14.0... yes
checking for qmi-glib >= 1.16.0... yes
checking for more warnings... yes
checking whether gcc understands -Wmissing-declarations... yes
checking whether gcc understands -Wmissing-prototypes... yes
checking whether gcc understands -Wdeclaration-after-statement... yes
checking whether gcc understands -Wstrict-prototypes... no
checking whether gcc understands -Wno-unused-parameter... yes
checking whether gcc understands -Wno-sign-compare... yes
checking whether gcc understands -Wno-deprecated-declarations... yes
checking whether gcc understands -Wno-unused-but-set-variable... yes
checking whether gcc understands -Wformat-security... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating data/ModemManager.pc
config.status: creating data/mm-glib.pc
config.status: creating data/org.freedesktop.ModemManager1.policy.in
config.status: creating data/tests/Makefile
config.status: creating data/tests/org.freedesktop.ModemManager1.service
config.status: creating include/Makefile
config.status: creating include/ModemManager-version.h
config.status: creating build-aux/Makefile
config.status: creating libqcdm/Makefile
config.status: creating libqcdm/src/Makefile
config.status: creating libqcdm/tests/Makefile
config.status: creating libwmc/Makefile
config.status: creating libwmc/src/Makefile
config.status: creating libwmc/tests/Makefile
config.status: creating src/Makefile
config.status: creating src/tests/Makefile
config.status: creating plugins/Makefile
config.status: creating uml290/Makefile
config.status: creating test/Makefile
config.status: creating introspection/Makefile
config.status: creating introspection/tests/Makefile
config.status: creating po/Makefile.in
config.status: creating docs/Makefile
config.status: creating docs/man/Makefile
config.status: creating docs/reference/Makefile
config.status: creating docs/reference/api/Makefile
config.status: creating docs/reference/api/version.xml
config.status: creating docs/reference/libmm-glib/Makefile
config.status: creating docs/reference/libmm-glib/version.xml
config.status: creating libmm-glib/Makefile
config.status: creating libmm-glib/generated/Makefile
config.status: creating libmm-glib/generated/tests/Makefile
config.status: creating libmm-glib/tests/Makefile
config.status: creating vapi/Makefile
config.status: creating cli/Makefile
config.status: creating examples/Makefile
config.status: creating examples/modem-watcher-python/Makefile
config.status: creating examples/modem-watcher-javascript/Makefile
config.status: creating examples/sms-python/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: executing po/stamp-it commands

    ModemManager 1.6.12
    ==============================================

    Build:
      compiler:                gcc
      cflags:                  -Wall -Werror -std=gnu89  -O2 -march=x86-64 -pipe -Wmissing-declarations -Wmissing-prototypes -Wdeclaration-after-statement -Wno-unused-parameter -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-but-set-variable -Wformat-security
      ldflags:                  -s
      maintainer mode:         yes

    System paths:
      prefix:                  /usr
      D-Bus system directory:  /etc/dbus-1/system.d
      udev base directory:     /usr/lib/udev
      systemd unit directory:  /usr/lib/systemd/system

    Features:
      policykit support:       permissive
      mbim support:            yes
      qmi support:             yes
      suspend/resume support:  systemd

    Miscellaneous:
      gobject introspection:   yes
      vala bindings:           yes
      documentation:           no
      code coverage:           no

/usr/bin/make  all-recursive
make[1]: Entering directory '/usr/src/ModemManager-1.6.12'
Making all in .
make[2]: Entering directory '/usr/src/ModemManager-1.6.12'
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12'
Making all in build-aux
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/build-aux'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/build-aux'
Making all in data
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/data'
Making all in .
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/data'
cp -f ../data/org.freedesktop.ModemManager1.conf.polkit org.freedesktop.ModemManager1.conf
  ITMRG  org.freedesktop.ModemManager1.policy
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/data'
Making all in tests
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/data/tests'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/data/tests'
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/data'
Making all in include
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/include'
Making all in libqcdm
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/libqcdm'
Making all in src
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libqcdm/src'
  CC       libqcdm_la-com.lo
  CC       libqcdm_la-errors.lo
  CC       libqcdm_la-result.lo
  CC       libqcdm_la-commands.lo
  CC       libqcdm_la-utils.lo
  CC       libqcdm_test_la-utils.lo
  CCLD     libqcdm-test.la
  CCLD     libqcdm.la
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libqcdm/src'
Making all in tests
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libqcdm/tests'
  CC       test_qcdm-test-qcdm-crc.o
  CC       test_qcdm-test-qcdm-escaping.o
  CC       test_qcdm-test-qcdm-utils.o
  CC       test_qcdm-test-qcdm-com.o
  CC       test_qcdm-test-qcdm-result.o
  CC       test_qcdm-test-qcdm.o
  CC       modepref-modepref.o
  CC       ipv6pref-ipv6pref.o
  CC       reset-reset.o
  CCLD     test-qcdm
  CCLD     modepref
  CCLD     reset
  CCLD     ipv6pref
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libqcdm/tests'
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libqcdm'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libqcdm'
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/libqcdm'
Making all in libwmc
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/libwmc'
Making all in src
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libwmc/src'
  CC       libwmc_la-errors.lo
  CC       libwmc_la-result.lo
  CC       libwmc_la-com.lo
  CC       libwmc_la-utils.lo
  CC       libwmc_la-commands.lo
  CCLD     libwmc.la
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libwmc/src'
Making all in tests
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libwmc/tests'
  CC       test_wmc-test-wmc-crc.o
  CC       test_wmc-test-wmc-escaping.o
  CC       test_wmc-test-wmc-utils.o
  CC       test_wmc-test-wmc.o
  CC       test_wmc-test-wmc-com.o
  CCLD     test-wmc
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libwmc/tests'
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libwmc'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libwmc'
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/libwmc'
Making all in libmm-glib
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib'
Making all in generated
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated'
  GEN      mm-enums-types.h
  GEN      mm-errors-types.h
  GEN      mm-gdbus-manager.c
  GEN      mm-gdbus-sim.c
  GEN      mm-gdbus-sms.c
  GEN      mm-gdbus-call.c
  GEN      mm-gdbus-bearer.c
  GEN      mm-gdbus-modem.c
  GEN      mm-errors-types.c
  GEN      mm-errors-quarks.c
  GEN      mm-enums-types.c
/usr/bin/make  all-recursive
make[4]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated'
Making all in .
make[5]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated'
  CC       libmm_generated_la-mm-enums-types.lo
  CC       libmm_generated_la-mm-errors-types.lo
  CC       libmm_generated_la-mm-gdbus-manager.lo
  CC       libmm_generated_la-mm-errors-quarks.lo
  CC       libmm_generated_la-mm-gdbus-sim.lo
  CC       libmm_generated_la-mm-gdbus-sms.lo
  CC       libmm_generated_la-mm-gdbus-call.lo
  CC       libmm_generated_la-mm-gdbus-bearer.lo
  CC       libmm_generated_la-mm-gdbus-modem.lo
  CCLD     libmm-generated.la
make[5]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated'
Making all in tests
make[5]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated/tests'
  GEN      mm-gdbus-test.h
  GEN      mm-gdbus-test.c
/usr/bin/make  all-am
make[6]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated/tests'
  CC       libmm_test_generated_la-mm-gdbus-test.lo
  CCLD     libmm-test-generated.la
make[6]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated/tests'
make[5]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated/tests'
make[4]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated'
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib/generated'
Making all in .
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib'
  CC       libmm_glib_la-mm-helper-types.lo
  CC       libmm_glib_la-mm-manager.lo
  CC       libmm_glib_la-mm-modem.lo
  CC       libmm_glib_la-mm-modem-3gpp.lo
  CC       libmm_glib_la-mm-object.lo
  CC       libmm_glib_la-mm-modem-3gpp-ussd.lo
  CC       libmm_glib_la-mm-modem-cdma.lo
  CC       libmm_glib_la-mm-modem-simple.lo
  CC       libmm_glib_la-mm-modem-location.lo
  CC       libmm_glib_la-mm-modem-time.lo
  CC       libmm_glib_la-mm-modem-firmware.lo
  CC       libmm_glib_la-mm-modem-signal.lo
  CC       libmm_glib_la-mm-modem-oma.lo
  CC       libmm_glib_la-mm-sim.lo
  CC       libmm_glib_la-mm-sms.lo
  CC       libmm_glib_la-mm-modem-messaging.lo
  CC       libmm_glib_la-mm-modem-voice.lo
  CC       libmm_glib_la-mm-call.lo
  CC       libmm_glib_la-mm-bearer.lo
  CC       libmm_glib_la-mm-common-helpers.lo
  CC       libmm_glib_la-mm-simple-status.lo
  CC       libmm_glib_la-mm-bearer-properties.lo
  CC       libmm_glib_la-mm-simple-connect-properties.lo
  CC       libmm_glib_la-mm-sms-properties.lo
  CC       libmm_glib_la-mm-call-properties.lo
  CC       libmm_glib_la-mm-bearer-ip-config.lo
  CC       libmm_glib_la-mm-bearer-stats.lo
  CC       libmm_glib_la-mm-location-3gpp.lo
  CC       libmm_glib_la-mm-location-gps-raw.lo
  CC       libmm_glib_la-mm-location-gps-nmea.lo
  CC       libmm_glib_la-mm-location-cdma-bs.lo
  CC       libmm_glib_la-mm-unlock-retries.lo
  CC       libmm_glib_la-mm-network-timezone.lo
  CC       libmm_glib_la-mm-firmware-properties.lo
  CC       libmm_glib_la-mm-cdma-manual-activation-properties.lo
  CC       libmm_glib_la-mm-signal.lo
  CCLD     libmm-glib.la
  GISCAN   ModemManager-1.0.gir
  GICOMP   ModemManager-1.0.gir
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib'
Making all in tests
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/libmm-glib/tests'
  CC       test_common_helpers-test-common-helpers.o
  CCLD     test-common-helpers
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib/tests'
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/libmm-glib'
Making all in src
make[2]: Entering directory '/usr/src/ModemManager-1.6.12/src'
  GEN      mm-port-enums-types.h
  GEN      mm-daemon-enums-types.h
  GEN      mm-port-enums-types.c
  GEN      mm-daemon-enums-types.c
/usr/bin/make  all-recursive
make[3]: Entering directory '/usr/src/ModemManager-1.6.12/src'
Making all in .
make[4]: Entering directory '/usr/src/ModemManager-1.6.12/src'
  CC       mm-charsets.lo
  CC       mm-modem-helpers.lo
  CC       mm-error-helpers.lo
  CC       mm-sms-part-3gpp.lo
  CC       mm-sms-part.lo
  CC       mm-sms-part-cdma.lo
  CC       mm-modem-helpers-qmi.lo
  CC       mm-modem-helpers-mbim.lo
  CC       mm-port.lo
  CC       mm-port-serial.lo
  CC       mm-port-serial-at.lo
  CC       mm-port-serial-qcdm.lo
  CC       mm-port-serial-gps.lo
  CC       mm-serial-parsers.lo
  CC       mm-port-qmi.lo
  CC       mm-port-mbim.lo
  CC       mm-port-enums-types.lo
  CC       ModemManager-main.o
  CC       ModemManager-mm-context.o
  CC       ModemManager-mm-log.o
  CC       ModemManager-mm-private-boxed-types.o
  CC       ModemManager-mm-auth.o
  CC       ModemManager-mm-auth-provider.o
  CC       ModemManager-mm-base-manager.o
  CC       ModemManager-mm-device.o
  CC       ModemManager-mm-plugin-manager.o
  CC       ModemManager-mm-base-sim.o
  CC       ModemManager-mm-base-bearer.o
  CC       ModemManager-mm-broadband-bearer.o
  CC       ModemManager-mm-bearer-list.o
  CC       ModemManager-mm-base-modem-at.o
  CC       ModemManager-mm-base-modem.o
  CC       ModemManager-mm-base-sms.o
  CC       ModemManager-mm-base-call.o
  CC       ModemManager-mm-sms-list.o
  CC       ModemManager-mm-call-list.o
  CC       ModemManager-mm-iface-modem.o
  CC       ModemManager-mm-iface-modem-3gpp.o
  CC       ModemManager-mm-iface-modem-3gpp-ussd.o
  CC       ModemManager-mm-iface-modem-cdma.o
  CC       ModemManager-mm-iface-modem-simple.o
  CC       ModemManager-mm-iface-modem-location.o
  CC       ModemManager-mm-iface-modem-messaging.o
  CC       ModemManager-mm-iface-modem-voice.o
  CC       ModemManager-mm-iface-modem-time.o
  CC       ModemManager-mm-iface-modem-firmware.o
  CC       ModemManager-mm-iface-modem-signal.o
  CC       ModemManager-mm-iface-modem-oma.o
  CC       ModemManager-mm-broadband-modem.o
  CC       ModemManager-mm-port-probe.o
mm-base-manager.c: In function 'handle_set_logging':
mm-base-manager.c:680:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (manager);
               ^
mm-base-manager.c: In function 'handle_scan_devices':
mm-base-manager.c:736:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (manager);
               ^
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1036: ModemManager-mm-base-manager.o] Error 1
make[4]: *** Waiting for unfinished jobs....
mm-device.c: In function 'mm_device_get_plugin':
mm-device.c:629:47: error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
     return (self->priv->plugin ?
            ~~~~~~~~~~~~~~~~~~~~~               
             g_object_ref (self->priv->plugin) :
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
             NULL);
             ~~~~~                              
mm-device.c: In function 'mm_device_get_port_probe':
mm-device.c:666:42: error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
     return (probe ? g_object_ref (probe) : NULL);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1050: ModemManager-mm-device.o] Error 1
mm-base-sim.c: In function 'common_init_async':
mm-base-sim.c:1531:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (initable);
               ^
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1078: ModemManager-mm-base-sim.o] Error 1
mm-broadband-bearer.c: In function 'connect':
mm-broadband-bearer.c:1255:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-bearer.c: In function 'disconnect':
mm-broadband-bearer.c:1820:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-bearer.c: In function 'initable_init_async':
mm-broadband-bearer.c:2037:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (initable);
               ^
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1106: ModemManager-mm-broadband-bearer.o] Error 1
++ Mark Compile stop   : "ModemManager" "1.6.12" "Fri, 18 May 2018 10:18:00 +0000"
mm-broadband-modem.c: In function 'modem_load_current_capabilities':
mm-broadband-modem.c:739:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_load_own_numbers':
mm-broadband-modem.c:1189:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_load_supported_modes':
mm-broadband-modem.c:1603:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_load_signal_quality':
mm-broadband-modem.c:1993:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_load_access_technologies':
mm-broadband-modem.c:2374:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_3gpp_load_enabled_facility_locks':
mm-broadband-modem.c:3392:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_3gpp_run_registration_checks':
mm-broadband-modem.c:4006:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_3gpp_ussd_send':
mm-broadband-modem.c:4647:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_messaging_load_initial_sms_parts':
mm-broadband-modem.c:6365:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_cdma_get_hdr_state':
mm-broadband-modem.c:6844:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_cdma_get_call_manager_state':
mm-broadband-modem.c:6972:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_cdma_get_cdma1x_serving_system':
mm-broadband-modem.c:7252:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_cdma_get_detailed_registration_state':
mm-broadband-modem.c:7526:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_cdma_setup_registration_checks':
mm-broadband-modem.c:7689:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'modem_cdma_register_in_network':
mm-broadband-modem.c:7863:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'disable':
mm-broadband-modem.c:9061:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     ctx->self = g_object_ref (self);
               ^
mm-broadband-modem.c: In function 'enable':
mm-broadband-modem.c:9461:19: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
         ctx->self = g_object_ref (self);
                   ^
mm-broadband-modem.c: In function 'initialize':
mm-broadband-modem.c:9953:19: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
         ctx->self = g_object_ref (self);
                   ^
cc1: all warnings being treated as errors
make[4]: *** [Makefile:1386: ModemManager-mm-broadband-modem.o] Error 1
make[4]: Leaving directory '/usr/src/ModemManager-1.6.12/src'
make[3]: *** [Makefile:1629: all-recursive] Error 1
make[3]: Leaving directory '/usr/src/ModemManager-1.6.12/src'
make[2]: *** [Makefile:753: all] Error 2
make[2]: Leaving directory '/usr/src/ModemManager-1.6.12/src'
make[1]: *** [Makefile:536: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/ModemManager-1.6.12'
make: *** [Makefile:468: all] Error 2

`

**Comment by Florin65** [comment]
Version was bumped to 1.8-rc2.
Thank you for the notification.
