### ISSUE TITLE
budgie-desktop compiling errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#56]
I tried to install Budgie. I have resolved the dependency but I get some errors:

> Checking dependencies for budgie-desktop 
Building budgie-desktop version 10.4
patching file src/session/meson.build
patching file src/wm/meson.build
patching file vapi/libmutter-2.deps
patching file vapi/libmutter-2.vapi
patching file src/panel/settings/settings_main.vala
/var/lib/lunar/moonbase/gnome3/apps/budgie-desktop/BUILD:line 1: default_meson_build: command not found
> 

@Florin65

**Comment by lhw828** [comment]
When i change the BUILD to "meson build",I try to lin budgie-desktop,logs show this:

> Build started at 2018-06-23T14:12:10.763970
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.46.0
Source dir: /usr/src/budgie-desktop-10.4
Build dir: /usr/src/budgie-desktop-10.4/build
Build type: native build
Project name: budgie-desktop
Sanity testing C compiler: gcc
Is cross compiler: False.
Sanity check compiler command line: gcc /usr/src/budgie-desktop-10.4/build/meson-private/sanitycheckc.c -o /usr/src/budgie-desktop-10.4/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /usr/src/budgie-desktop-10.4/build/meson-private/sanitycheckc.exe
Native C compiler: gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending LDFLAGS from environment: ' -s'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Running compile:
Working directory:  /tmp/tmpr1dju0xz
Command line:  valac /tmp/tmpr1dju0xz/testfile.vala -C 

Code:
 class MesonSanityCheck : Object { }
Compiler stdout:
 
Compiler stderr:
 
Native Vala compiler: valac (valac 0.40.7)
Appending LDFLAGS from environment: ' -s'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Program meson_post_install.sh found: YES (/usr/src/budgie-desktop-10.4/meson_post_install.sh)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gtk+-3.0 found: YES 3.22.30
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency glib-2.0 found: YES 2.56.1
Determining dependency 'gio-unix-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gio-unix-2.0 found: YES 2.56.1
Determining dependency 'libpeas-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libpeas-1.0 found: YES 1.22.0
Determining dependency 'gdk-x11-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gdk-x11-3.0 found: YES 3.22.30
Determining dependency 'uuid' with pkg-config executable '/usr/bin/pkg-config'
Native dependency uuid found: YES 2.32.0
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gtk+-3.0 found: NO found '3.22.30' but need: '< 3.19'
Dependency gtk+-3.0 found: NO
meson.build:49: WARNING: Passed invalid keyword argument "verion".
WARNING: This will become a hard error in the future.
Determining dependency 'ibus-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency ibus-1.0 found: YES 1.5.17
Determining dependency 'gnome-desktop-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gnome-desktop-3.0 found: YES 3.28.0
Determining dependency 'gsettings-desktop-schemas' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gsettings-desktop-schemas found: YES 3.28.0
Determining dependency 'libwnck-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libwnck-3.0 found: YES 3.24.1
Determining dependency 'accountsservice' with pkg-config executable '/usr/bin/pkg-config'
Native dependency accountsservice found: YES 0.6.47
Running command: /usr/bin/git describe
--- stdout----

----stderr----
fatal: 不是一个 git 仓库（或者任何父目录）：.git


Program intltool-merge found: YES (/usr/bin/intltool-merge)
Configuring config.h using configuration


Executing subproject gvc.

Project name: gvc
Native C compiler: gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending LDFLAGS from environment: ' -s'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Determining dependency 'libpulse' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libpulse found: YES 12.0-rebootstrapped
Determining dependency 'libpulse-mainloop-glib' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libpulse-mainloop-glib found: YES 12.0-rebootstrapped

subprojects/gvc/meson.build:31:0: ERROR:  Sandbox violation: Tried to grab file gvc-channel-map.c from a different subproject.

> 

>

**Comment by lhw828** [comment]
Building budgie-desktop version 10.4
patching file src/session/meson.build
patching file src/wm/meson.build
patching file vapi/libmutter-2.deps
patching file vapi/libmutter-2.vapi
patching file src/panel/settings/settings_main.vala
The Meson build system
Version: 0.46.0
Source dir: /usr/src/budgie-desktop-10.4
Build dir: /usr/src/budgie-desktop-10.4/build
Build type: native build
Project name: budgie-desktop
Native C compiler: gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
Appending LDFLAGS from environment: ' -s'
Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
Native Vala compiler: valac (valac 0.40.7)
Appending LDFLAGS from environment: ' -s'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Program meson_post_install.sh found: YES (/usr/src/budgie-desktop-10.4/meson_post_install.sh)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gio-unix-2.0 found: YES 2.56.1
Native dependency libpeas-1.0 found: YES 1.22.0
Native dependency gdk-x11-3.0 found: YES 3.22.30
Native dependency uuid found: YES 2.32.0
Native dependency gtk+-3.0 found: NO found '3.22.30' but need: '< 3.19'
Dependency gtk+-3.0 found: NO
Native dependency ibus-1.0 found: YES 1.5.17
Native dependency gnome-desktop-3.0 found: YES 3.28.0
Native dependency gsettings-desktop-schemas found: YES 3.28.0
Native dependency libwnck-3.0 found: YES 3.24.1
Native dependency accountsservice found: YES 0.6.47
Program intltool-merge found: YES (/usr/bin/intltool-merge)
Configuring config.h using configuration

|
|Executing subproject gvc.
|
|Project name: gvc
|Native C compiler: gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
|Appending CFLAGS from environment: ' -O2 -march=x86-64 -pipe'
|Appending LDFLAGS from environment: ' -s'
|Appending CPPFLAGS from environment: ' -D_FORTIFY_SOURCE=2'
|Native dependency libpulse found: YES 12.0-rebootstrapped
|Native dependency libpulse-mainloop-glib found: YES 12.0-rebootstrapped

subprojects/gvc/meson.build:31:0: ERROR:  Sandbox violation: Tried to grab file gvc-channel-map.c from a different subproject.

A full log can be found at /usr/src/budgie-desktop-10.4/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/budgie-desktop-10.4.xz 

[budgie-desktop-10.4.log](https://github.com/lunar-linux/moonbase-gnome3/files/2153547/budgie-desktop-10.4.log)


In fact, I already have the latest version of GTK+-3.

**Comment by lhw828** [comment]
https://aur.archlinux.org/packages/budgie-desktop-git/

It seems an old bug. @Florin65

**Comment by lhw828** [comment]
@Florin65 [https://data.gpo.zugaina.org/wjn-overlay/gnome-extra/budgie-desktop/budgie-desktop-10.4.ebuild](url)

`src_prepare() {
	default

	# Meson bug workaround
	cp -R src/gvc subprojects/gvc/ || die
	sed -i -e 's:../../src/::g' \
		subprojects/gvc/meson.build || die

	vala_src_prepare
}`


This piece of code can inspire us to solve that bug?

**Comment by Florin65** [comment]
There is another ticket on the new version of the module. Close now this one.
