### ISSUE TITLE
webkit2gtk3:Unable to compile properly

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#87]
[ 78%] Generating ../../DerivedSources/WebKit/LegacyCustomProtocolManagerProxyMessageReceiver.cpp, ../../DerivedSources/WebKit/LegacyCustomProtocolManagerProxyMessages.h
Traceback (most recent call last):
  File "/usr/src/webkitgtk-2.20.5/webkit2gtk3-oosb/DerivedSources/ForwardingHeaders/JavaScriptCore/Scripts/cssmin.py", line 49, in <module>
    sys.stdout.write(cssminify(sys.stdin.read()))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 22793: ordinal not in range(256)
Failed to minify /usr/src/webkitgtk-2.20.5/webkit2gtk3-oosb/DerivedSources/WebInspectorUI/Main.css: Inappropriate ioctl for device at /usr/src/webkitgtk-2.20.5/Source/WebInspectorUI/Scripts/copy-user-interface-resources.pl line 291.
make[2]: *** [Source/WebKit/CMakeFiles/WebKit.dir/build.make:2191: inspector-resources.stamp] Error 25
make[1]: *** [CMakeFiles/Makefile2:1304: Source/WebKit/CMakeFiles/WebKit.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
Creating /var/log/lunar/compile/webkit2gtk3-2.20.5.xz

**Comment by lazyape** [comment]
Hi lhw828

I had this problem too and i change LANG env var to en_US.utf8
can you please try to use a LANG that is utf8?
If this works for you then we should add a check regarding this
particular env var
