### ISSUE TITLE
budgie-desktop:Can we use the Ubuntu's source code to build budgie?

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#98]
budgie-desktop:Can we use the Ubuntu's source code to build budgie?

https://packages.ubuntu.com/source/cosmic/budgie-desktop

http://archive.ubuntu.com/ubuntu/pool/universe/b/budgie-desktop/budgie-desktop_10.4+git20180830.02.f2dbc215fdb.orig.tar.xz

@Florin65  Can you use this package to build budgie?

**Comment by Florin65** [comment]
Modified the module to use the requested source.
The module still need more work/testing.

**Comment by lhw828** [comment]
> Modified the module to use the requested source.
> The module still need more work/testing.

I still can't compile and install budgie properly.

**Comment by Florin65** [comment]
Yes, that's why it needs more work.

**Comment by fossfreedom** [comment]
If you are going to build using Ubuntu Budgie's tarball - you'll need to patch it as well (for mutter 3.30 and later) - 

https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/budgie-desktop/10.4+git20180830.02.f2dbc215fdb-2/budgie-desktop_10.4+git20180830.02.f2dbc215fdb-2.debian.tar.xz

debian/patches folder

HTH

**Comment by lhw828** [comment]
> If you are going to build using Ubuntu Budgie's tarball - you'll need to patch it as well (for mutter 3.30 and later) -
> 
> https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/budgie-desktop/10.4+git20180830.02.f2dbc215fdb-2/budgie-desktop_10.4+git20180830.02.f2dbc215fdb-2.debian.tar.xz
> 
> debian/patches folder
> 
> HTH

https://github.com/lunar-linux/moonbase-gnome3/tree/master/apps/budgie-desktop/patch.d

It seems that step has been completed, but there are still problems. Can you participate in the testing of this module?

Thank you！ @fossfreedom

**Comment by fossfreedom** [comment]
There are many more patches in the debian.tar.gz that you will need to apply

On Tue, 4 Dec 2018, 03:46 lhw828 <notifications@github.com<mailto:notifications@github.com> wrote:

If you are going to build using Ubuntu Budgie's tarball - you'll need to patch it as well (for mutter 3.30 and later) -

https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/budgie-desktop/10.4+git20180830.02.f2dbc215fdb-2/budgie-desktop_10.4+git20180830.02.f2dbc215fdb-2.debian.tar.xz

debian/patches folder

HTH

https://github.com/lunar-linux/moonbase-gnome3/tree/master/apps/budgie-desktop/patch.d

It seems that step has been completed, but there are still problems. Can you participate in the testing of this module?

Thank you！ @fossfreedom<https://github.com/fossfreedom>

**Comment by fossfreedom** [comment]
Ah -  ok - I see you have grabbed all the patches.  Excellent.  So what issues are you having when building?

**Comment by lhw828** [comment]
@fossfreedom The error prompt at this stage is as follows:

https://github.com/lunar-linux/moonbase-gnome3/pull/100

**Comment by fossfreedom** [comment]
/usr/local/share/applications/

What are your meson build rules?  Mine is this:

`meson -Dwith-desktop-icons=none --buildtype plain --prefix=/usr --libdir=/usr/lib --sysconfdir=/etc`

i.e. compile and install stuff into /usr/lib locations - not the default /usr/local
