### ISSUE TITLE
webkit2gtk3-2.22.4:some errors.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-gnome3#99]
Scanning dependencies of target PluginProcess
[ 97%] Building CXX object Source/WebKit/CMakeFiles/PluginProcess.dir/PluginProcess/EntryPoint/unix/PluginProcessMain.cpp.o
Scanning dependencies of target StorageProcess
Traceback (most recent call last):
  File "/usr/src/webkitgtk-2.22.4/Tools/gtk/generate-gtkdoc", line 19, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
make[2]: *** [Source/CMakeFiles/gtkdoc.dir/build.make:63：docs-build.stamp] 错误 1
make[1]: *** [CMakeFiles/Makefile2:117：Source/CMakeFiles/gtkdoc.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 97%] Building CXX object Source/WebKit/CMakeFiles/StorageProcess.dir/StorageProcess/EntryPoint/unix/StorageProcessMain.cpp.o
[ 97%] Linking CXX executable ../../bin/WebKitPluginProcess
[ 97%] Linking CXX executable ../../bin/WebKitStorageProcess
[ 97%] Built target PluginProcess
[ 97%] Built target StorageProcess
/usr/include/glib-2.0/gobject/gobject.h:725: syntax error, unexpected ')' in '    ((__typeof__(new_object)) (g_object_ref) (new_object));' at ')'
/usr/include/glib-2.0/gobject/gobject.h:725: syntax error, unexpected ')' in '    ((__typeof__(new_object)) (g_object_ref) (new_object));' at ')'
[ 97%] Generating ../../WebKit2WebExtension-4.0.gir
[ 97%] Generating ../../WebKit2-4.0.typelib
[ 97%] Built target WebKit2-4-gir
/usr/include/glib-2.0/gobject/gobject.h:725: syntax error, unexpected ')' in '    ((__typeof__(new_object)) (g_object_ref) (new_object));' at ')'
[ 97%] Generating ../../WebKit2WebExtension-4.0.typelib
[ 97%] Built target WebKit2WebExtension-4-gir
make: *** [Makefile:152：all] error 2

**Comment by lazyape** [comment]
should be fixed by installing upstream gobject-introspection (at the time of writing its version is 1.58.3)
